### PR TITLE
v0.12.0

### PR DESCRIPTION
**Pull request by marcelklehr**
Changelog:

- NEW UI
  - bulk actions
  - webpage previews and favicons
  - bookmark search
  - configurable sorting
  - view all untagged bookmarks
- NEW: option to remove all bookmarks
- NEW: Allow fetching bookmark query results as RSS feeds
- FIX: Various fixes to import/export

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by marcelklehr** [comment]
:rocket:

**Comment by blizzz** [comment]
you didn't merge it?

**Comment by marcelklehr** [comment]
I merged it manually. For some reason github didn't pick up on it.

**Comment by blizzz** [comment]
Oki

**Pull request closed without merging**
