### PR TITLE
Fix RepairStep: Reinsert lost bookmarks instead of deleting

### PR DESCRIPTION
**Pull request by marcelklehr**
Signed-off-by: Marcel Klehr <mklehr@gmx.net>

### CODE REVIEW

**Comment by susinths** [comment]
Looks good to me from an upgrade from NC19 and bookmarks v3.4.9 to NC20 and bookmarks v4.1.0 :+1:

**Comment by radoeka** [comment]
Would it be possible to complete the merge?  Only 1 check to go (php7.4-sqlite-stable20).

**Comment by marcelklehr** [comment]
The reason it hasn't been merged, yet is pending code reviews :)

(ping @ChristophWurst, @blizzz, @stijink )

**Comment by radoeka** [comment]
When I'm not mistaken (after reading the code), the reinserted bookmark is stored in the root folder.  
Would it be possible to store it in an orphaned bookmark folder?  And or give it the tag orphaned?

Having it stored in a "Orphaned Bookmarks" folder (and/or tagged with orphaned) it will be much easier to find it and reorganize it back into the folder structure.

**Comment by stijink** [comment]
@marcelklehr I would recommend to add a functional test. Is this possible with nextcloud ?

**Comment by marcelklehr** [comment]
@stijink That's a good idea! There's basic CI for repair steps: https://github.com/nextcloud/bookmarks/blob/master/.github/workflows/repair.yml

This imports a basic folder structure into the app, runs the repair steps and compares the API-returned tree structure from before and after repair steps. Do you think we need a specific test to make sure this legacy migration works?

**Comment by marcelklehr** [comment]
@stijink I've added a test :heart:

**Comment by marcelklehr** [comment]
@radoeka we can iterate over this in the future. For now, let's make sure people don't lose their bookmarks anymore.

**Comment by marcelklehr** [comment]
@ChristophWurst @blizzz Could you take a look at this? @stijink is not available at the moment :)

**Comment by marcelklehr** [comment]
#mergetime

**Pull request merged**
