### PR TITLE
Adjust tests for phpunit

### PR DESCRIPTION
**Pull request by blizzz**
Since they started to fail…

### CODE REVIEW

**Comment by marcelklehr** [comment]
Mh, things are failing that didn't fail before, right? Weird.

**Comment by blizzz** [comment]
Exactly. But now we are down to failing rename tests again, which is expected \o/ Plus, failing OC tests, because their master is 10. Since we got an error report in this regard (https://github.com/nextcloud/bookmarks/issues/341) and an [extremely hostile post by assumingly on of their officials](https://central.owncloud.org/t/nextcloud-bookmark-app-calles-undefined-methode/5724/2) I am pretty open for dropping this support at all, at least of no contributions comes from that side. Anyway, with the latest commit I increased max-version for oc for now, let's see how these tests go.

**Comment by blizzz** [comment]
For one it was PHP 5.5 running out of life that caused fails, and I also took over https://github.com/nextcloud/activity/pull/126 from the activity app.

**Comment by blizzz** [comment]
Now there is just one unexpected one missing, being OC 9.1 against PHP 7/sqlite. Seems that goes with a newer phpunit version that tries to load a file which is not there anymore.

**Comment by blizzz** [comment]
I put the one failing OC test as allowed (for now).

**Pull request merged**
