### PR TITLE
API docs: Document breaking changes in v3

### PR DESCRIPTION
**Pull request by marcelklehr**
@dasbiswajit Could you check if there's anything else that I've missed here?

### CODE REVIEW

**Comment by marcelklehr** [comment]
cc @dgmid @mario

**Comment by dasbiswajit** [comment]
Sure. Sorry missed that will have a look.

**Comment by altepizza** [comment]
Thx! Going to prepare my app.

**Comment by marcelklehr** [comment]
@altepizza oh, you probably have these changes already, if your app works with the latest release. I just wanted to document the changes, in case other's are late to the party.

**Comment by altepizza** [comment]
Alright
Will either way spend some time with my code. Thx for the little push :P

**Comment by marcelklehr** [comment]
@altepizza Do you remember anything else that you had to change?

**Comment by dasbiswajit** [comment]
@marcelklehr I have checked only one changes is there for v3 Api from v2 for [Bookmark Android app](https://gitlab.com/bisada/OCBookmarks/-/commit/d7bc6cdbdd70fc63594df76eb9e09c7cf5866465)

**Comment by marcelklehr** [comment]
@dasbiswajit Thanks! Didn't you have trouble with Authentication as well?

**Pull request merged**
