### PR TITLE
Sharing UI

### PR DESCRIPTION
**Pull request by marcelklehr**
Sharing user:
Screenshot from 2020-03-31 14-39-24
Screenshot from 2020-03-31 14-40-39

Sharee:

Screenshot from 2020-03-31 14-40-00

Public link
Screenshot from 2020-03-31 14-43-03

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Wow, this is very very cool! My only feedback is kinda unrelated. :D
- On the sharing page, the title subline is black but should be white
- Instead of breadbrumbs, we should use the system that Photos uses with the nice large headings

So :+1: from me

**Comment by skjnldsv** [comment]
> * Instead of breadbrumbs, we should use the system that Photos uses with the nice large headings

I think there is an issue already.
Let's stay relevant to this issue ;)

**Comment by jancborchardt** [comment]
> > * Instead of breadbrumbs, we should use the system that Photos uses with the nice large headings
> 
> I think there is an issue already.
> Let's stay relevant to this issue ;)

Exactly why I simply gave my :+1: and said it’s unrelated. ;)

**Comment by marcelklehr** [comment]
Ah, nice I hadn't seen the photos app approach, yet :)

> On the sharing page, the title subline is black but should be white

I was baffled by that as well. I'm using the PublicPageTemplate to set those, so I wasn't sure whether I should style that myself, or if this is an upstream bug.

**Comment by skjnldsv** [comment]
Please rebase ;)
Tests should be running now, I feel more confident reviewing this pr now :)

**Comment by marcelklehr** [comment]
The server-side tests are broken, atm, I will work on this laters

**Comment by marcelklehr** [comment]
I should get those complexity numbers down... :sweat_smile:

**Comment by jancborchardt** [comment]
So @skjnldsv will be able to talk about this more, but the Sharing UI would be a good candidate for a component in the Vue components library :) https://github.com/nextcloud/nextcloud-vue

**Comment by marcelklehr** [comment]
@skjnldsv This is good to review now :)

**Comment by ccoenen** [comment]
`omg-its-happening.gif` here. Thanks everyone! Looking forward to the release!

**Comment by jancborchardt** [comment]
Props @marcelklehr, really good work! :)

**Pull request merged**
