### PR TITLE
WIP: Implement folders

### LINKED ISSUE #514: Add "Folders" to Bookmarks to collect Bookmarks into Categories
As #13 already requested:

> To help me organize my Bookmarks, I'd like to request a new "Folder" feature in Bookmarks so I can group related Bookmarks together.

That issue was marked as resolved by @jancborchardt pointing to "tags":

> There are "Tags" in Bookmarks, which cater to the use-case of "group related Bookmarks together" which was mentioned in the original issue.

That quote is taken out of context IMHO. Tags are admitteldy a way to organize bookmarks, but definitely not what that issue was about or what the vast majority of participants (including the OP, who even included a graphic depicturing **folders** (not tags!) in his opening post) stated to need – see e.g. [this comment](https://github.com/nextcloud/bookmarks/issues/13#issuecomment-383866127) by @prog-amateur or [this one](https://github.com/nextcloud/bookmarks/issues/13#issuecomment-380034563) by @Lantizia. [Quoting](https://github.com/nextcloud/bookmarks/issues/13#issuecomment-353068968) @v3nd3tta1337:

> IMO Nextcloud Bookmarks is completely useless to users without having folders.
[…] If I want to search (for tags), i want to search (for tags), if i want to organize, i want to organize.

Those are just a few of the latest comments there, you can find plenty more showing clearly that "tags" are *not* the answer to the request for folders. I clearly cannot see how that issue was closed with that argument.

So could we please move forward with the folder topic?

<sub>If you feel this being a duplicate, please reopen the original and close this one. I don't know if we still can hope for bookmark folders, with the referenced issue standing there for more than 5 years unsolved (I guess most of the other participants of #13 already gave up on it). I'm not "demanding" it – but if you don't want to implement it, simply say so and don't pretend it's solved "differently" (no, bookmarks have *not* been replaced by Wallabag; that's a different concept altogether – bookmarks are for reference, not for "read it later"). Please don't take this as a rant, though admittedly I'm not especially happy with the situation. I've all respect for the Nexcloud team and contributors, and am glad to have Nextcloud!</sub>

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #514 

folders-preview

folders-preview2

- [x] API
- [x] Import
- [x] Export
- [x] UI
  - [x] move bookmarks
  - [x] move bookmark selections
  - [x] move folders
- [x] Migration
- [x] reorder children

### CODE REVIEW

**Comment by marcelklehr** [comment]
@nextcloud/designers @nextcloud/designlearners 

So, originally the idea was to display the folder hierarchy in the navigation sidebar. However, it turns out that it's not possible / desired to display more than two layers of hierarchy in the navigation sidebar. I'm grateful for alternative ideas. I had been thinking of doing something similar to the gallery app, but that never struck me as too elegant.

**Comment by stefan-niedermann** [comment]
maybe you can choose a similar solution lik @korelstar did with the notes app. the user interface only shows two layers while the api accepts deeper hirarchy

**Comment by marcelklehr** [comment]
@stefan-niedermann Thanks for your input! Jan just told me it would be ok to have deeper hierarchies. The reason to not implement this out of the box apparently was to discourage complex navigation structures. So, I'll add the necessary CSS for deeper nesting, then.

**Comment by jancborchardt** [comment]
@marcelklehr looking at the gif, you can save a whole level by simply showing the folders directly in the sidebar, without an expandable "Folders" folder. This is what the News app does too for example. It simplifies the interface a lot.

**Comment by marcelklehr** [comment]
@jancborchardt Ah, good idea. By default bookmarks end up in the root folder, though. I guess I could add an "uncategorized" folder for that, just like the "untagged" nav item. I'll remove the main tags nav item as well, then.

**Comment by marcelklehr** [comment]
You can now test this feature with the [v0.14.0-beta.1](https://github.com/nextcloud/bookmarks/releases/tag/v0.14.0-beta.1) release.

**Comment by microbrewer** [comment]
Hi everyone, first off, I love the idea of folders being added! :) I just installed the 0.14 release, but all I get is the "Uncategorized" folder. I don't see a way to create any folder on the web UI. 

Is this a bug or by design? Am I missing something obvious?

**Comment by marcelklehr** [comment]
@microbrewer No, sorry, I missed the obvious. After refactoring I forgot to re-add the button to create root-level folders. v0.14.1 has the button, now. Thanks for the heads-up! :)

**Comment by jancborchardt** [comment]
Btw @marcelklehr great work! :) Hope you will make it to the next Contributor Week (likely March 11–15) so we can work on this more!

**Pull request merged**
