### PR TITLE
Infinite scroll: Load the first 3 pages unconditionally in sequence

### PR DESCRIPTION
**Pull request by marcelklehr**
as per #495

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review @exekutive, as this is one step towards fixing what you reported at https://github.com/nextcloud/bookmarks/issues/495 :)

**Comment by exekutive** [comment]
I inserted the change. It loads 30 bookmarks and stops, waits for me to scroll to the bottom and then loads 30 more.

**Comment by marcelklehr** [comment]
You will need to [rebuild the app](https://github.com/nextcloud/bookmarks#manual-install), unless you insert the change in the bundled js file in `js/dist/`.

**Comment by exekutive** [comment]
I changed /js/dist/main.bundle.js

**Comment by marcelklehr** [comment]
Ah, my bad. Pushed a new version.

**Comment by exekutive** [comment]
so I should wait for a release?

**Comment by jancborchardt** [comment]
@exekutive you could manually apply the change and test it. Or are you running a local instance? (Then you could install it via git also)

**Comment by marcelklehr** [comment]
The changeset in this pull request has been updated, so you can try it again (it changed from `this` to `that` ;) )

**Comment by exekutive** [comment]
> you could manually apply the change and test it. Or are you running a local instance? 

> you can try it again (it changed this to that ;) )

I thought that is what I did when I changed /js/dist/main.bundle.js. It's running on a live remote server. Sorry I must not be understanding something.

The latest version I see is the one I installed 3 weeks ago (v0.12.0-rc1). Unless the only way to test this is building the app from source, in which case I'd rather just wait.

**Comment by marcelklehr** [comment]
Ah, sorry foor the confusion: You correctly applied the patch, but there's a mistake in there. Instead of `this`, the new code should read `that`. I've since updated the patch here on github, but it's of course very similar to the one you tried out. So, if you simply overtake the changes as they are now, into the main.bundle.js again, it should work.

**Comment by exekutive** [comment]
Got it. Thank you. Unfortunately, it still behaves the same.

**Comment by marcelklehr** [comment]
Mmh. :/ I assume something went wrong applying that patch, since it works for me.
I'll merge this for now, and you can observe it in action in the next (pre-)release.

**Comment by marcelklehr** [comment]
This has just hit the latest release candidate. Feel free to test and give feedback over here: https://github.com/nextcloud/bookmarks/issues/495

**Comment by jancborchardt** [comment]
Good stuff, thanks a lot for your work @marcelklehr! :)

**Comment by jancborchardt** [comment]
Btw @marcelklehr you are coming to the Nextcloud conference in Berlin, right? https://nextcloud.com/conf :) There’s travel/accomodation support for contributors as usual, and it would be great if you give a lightning talk (just max 5 minutes) about all the cool Bookmark app improvements! :tada:

**Comment by marcelklehr** [comment]
@jancborchardt Thanks :) Regarding the conference: I won't be there, I'm afraid.

**Comment by jancborchardt** [comment]
😭

**Pull request merged**
