### PR TITLE
Format Settings Text

### PR DESCRIPTION
**Pull request by meichthys**
- Bold settings headers
- Center button text
- Color destructive button as warning

### CODE REVIEW

**Comment by marcelklehr** [comment]
Hey @meichthys!
Thank you for taking the time to contribute! :)
While the changes in the UI look good, I'm not sure if the classes you used are intended for public consumption, as I couldn't find them in the docs.

I'll defer to @skjnldsv on this.

**Comment by meichthys** [comment]
Ok, yes, i fugured the classes might not be ideal, but rather than request that someone make the changes, i took a stab at it :) Great App!

**Comment by meichthys** [comment]
@skjnldsv Would you have a minute to look at these small styling changes?

**Comment by marcelklehr** [comment]
So sorry for the delay on this. I'd say, if we remove the bold classes in favor of a css rule in the bottom of the file, the rest is good to go :)

**Comment by meichthys** [comment]
All taken care of 👍

**Pull request merged**
