### PR TITLE
Only draw bulk actions when selection is active

### LINKED ISSUE #500: 0.12 RC1 freezes browser
… with the bookmarks from my instance. I anonymized tags, urls and titles and created a dump for testing: 
[bookmarks.sql.txt](https://github.com/nextcloud/bookmarks/files/2060085/bookmarks.sql.txt)

could not do further testing yet :(

@marcelklehr

### PR DESCRIPTION
**Pull request by marcelklehr**
especially not on page load. spares us of 3minutes of loading.gif

Fixes #500

### CODE REVIEW

**Comment by blizzz** [comment]
hm, still the same. at least i have the same suspicion that it's the js causing it

**Comment by marcelklehr** [comment]
Mmh. Browser == firefox?

**Comment by blizzz** [comment]
Will do, rather not today though, sorry for the delay.

**Comment by marcelklehr** [comment]
I'll merge this as is for now and we can see how to improve upon this once we have details on what is blocking the browser.

**Pull request merged**
