### PR TITLE
Release v0.12.0-rc1

### PR DESCRIPTION
**Pull request by marcelklehr**

### CODE REVIEW

**Comment by blizzz** [comment]
Can we kill  bookmarks/js/bookmarklet_old.js?

**Comment by blizzz** [comment]
Also when building, we can exclude everything in js, except for dist, correct?

**Comment by marcelklehr** [comment]
PHP 5 support is fixed.

**Comment by blizzz** [comment]
Another thing we can/should do: raise min-Nexcloud version to 12. All earliere series are EOL.

**Pull request merged**
