### PR TITLE
fixes #973

### LINKED ISSUE #973: Edit bookmark name in Details Menu
Screenshot_20200416_115828

I'd like to be able to edit the bookmark's title displayed just above the URL from within Details Menu.
This would allow the title to change from  `RCA-BNC adapter` to anything: `Turntable RCA-BNC adapter`.  No big deal, but thanks for considering

### PR DESCRIPTION
**Pull request by reimer-atb**
Signed-off-by: Philip Reimer <reimer@atb-bremen.de>

### CODE REVIEW

**Comment by marcelklehr** [comment]
Thanks for diving into the code and taking this on! :heart: 
It turns out the nextcloud vue components already have an implementation for this that we can simply make use of: https://nextcloud-vue-components.netlify.app/#/Components/App%20containers?id=appsidebar-1

Would you be willing to refactor your PR to use that API? :pray:

**Comment by philipreimer** [comment]
I'll give it a try

**Comment by marcelklehr** [comment]
@philipreimer Feel free to ping me on irc or gitter in case you're stuck. :relaxed:

**Comment by marcelklehr** [comment]
Rather than merging in the master branch, I recommend using git rebase, to avoid pulling in all these commits.

I've merged this by hand for now, though. Thanks! :heart:

**Pull request closed without merging**
