### PR TITLE
Fix tag list in sidebar in NC v13

### PR DESCRIPTION
**Pull request by marcelklehr**

### CODE REVIEW

**Comment by mlsimpson** [comment]
FWIW, I manually added this to the bookmarks.css and nothing changed

image

**Comment by marcelklehr** [comment]
Thanks for the feedback, this was a blind fix based on the code in the new release, without any tests ;)

Now, that i've been abel to lay my hands on a v13 instance, this should do the trick:

```css
#app-navigation > ul > li {
  display: block !important;
}
```

I'll update this pr laters.

**Comment by mlsimpson** [comment]
@marcelklehr That did the trick, thanks!

**Comment by 4oo4** [comment]
Fixed it for me too. Thank you!

**Comment by marcelklehr** [comment]
@radoeka this should fix the filtered tags ;)

**Comment by radoeka** [comment]
Fixed (but a forced renew of the page is needed).

**Comment by damko** [comment]
I suppose this PR is fixing the tags displayed in double column, right? why is it not merged to master yet?

**Comment by marcelklehr** [comment]
@damko it is now :) (I was waiting for @blizzz's blessing :D)

**Comment by blizzz** [comment]
Sorry, still catching up with backlog after being sick… thanks @marcelklehr!

**Comment by marcelklehr** [comment]
@blizzz Oh, I'm glad you're better now and happy you're back! :) :tada:

**Pull request merged**
