### PR TITLE
Fix bookmark creation

### LINKED ISSUE #69: Import does not update tags of existing bookmark OCV6.0.2
In summary, import works initially, import does add new bookmarks on subsequent imports, and import will add tags for new bookmarks that do not match an address of an existing book mark. If an import has a book mark with the same address of an existing bookmark, then the title will update, but tags will not update. I do also notice that the book marks are restored, so that subsequently imported bookmarks show at the top of the list, but with only the explain updated fields. 

To reproduce, put the following in a bookmark HTML file and import:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
    <DT><H3 ADD_DATE="1335302581" LAST_MODIFIED="1397672541" PERSONAL_TOOLBAR_FOLDER="true">Bookmarks Bar</H3>
    <DL><p>
        <DT><A HREF="https://www.google.com/" ADD_DATE="1397672503" >Google</A>
        <DT><A HREF="https://www.youtube.com/" ADD_DATE="1397672515" >YouTube</A>
        <DT><A HREF="https://identi.ca/" ADD_DATE="1397672519" >Welcome - Identi.ca</A>
        <DT><A HREF="https://drupal.org/" ADD_DATE="1397672523" >Drupal - Open Source CMS | Drupal.org</A>
        <DT><A HREF="http://symfony.com/" ADD_DATE="1397672526" >High Performance PHP Framework for Web Development - Symfony</A>
        <DT><A HREF="https://www.youtube.com/watch?v=l0oa_YtVLOc" ADD_DATE="1397672530" >ownCloud Demonstration - YouTube</A>
        <DT><A HREF="https://www.youtube.com/watch?v=70pCBnNPdew" ADD_DATE="1397672534" >ownCloud 6 New Features - YouTube</A>
        <DT><A HREF="https://www.youtube.com/watch?v=Pc9zB1mhPyQ" ADD_DATE="1397672537" >Create you own cloud storage using owncloud - YouTube</A>
        <DT><A HREF="https://www.youtube.com/watch?v=zcvU6EoKbaM" ADD_DATE="1397672541" >Build A Home Server For Your Music and Movies With FreeNAS! - YouTube</A>
    </DL><p>
</DL><p>
```

Next add a book mark, such as >> KDE.org << I did, which shows in my export:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
It will be read and overwritten.
Do Not Edit! -->
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p><DT><A HREF="http://kde.org/" TAGS="Desktop,FLOSS">KDE - Experience Freedom!</A>
<DT><A HREF="https://www.youtube.com/watch?v=zcvU6EoKbaM" TAGS="">Build A Home Server For Your Music and Movies With FreeNAS! - YouTube</A>
<DT><A HREF="https://www.youtube.com/watch?v=Pc9zB1mhPyQ" TAGS="">Create you own cloud storage using owncloud - YouTube</A>
<DT><A HREF="https://www.youtube.com/watch?v=70pCBnNPdew" TAGS="">ownCloud 6 New Features - YouTube</A>
<DT><A HREF="https://www.youtube.com/watch?v=l0oa_YtVLOc" TAGS="">ownCloud Demonstration - YouTube</A>
<DT><A HREF="http://symfony.com/" TAGS="">High Performance PHP Framework for Web Development - Symfony</A>
<DT><A HREF="https://drupal.org/" TAGS="">Drupal - Open Source CMS | Drupal.org</A>
<DT><A HREF="https://identi.ca/" TAGS="">Welcome - Identi.ca</A>
<DT><A HREF="https://www.youtube.com/" TAGS="">YouTube</A>
<DT><A HREF="https://www.google.com/" TAGS="">Google</A>
</DL><p>
```

Then open the file in a text editor and add some tags, e.g. to google.com, to be imported:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
It will be read and overwritten.
Do Not Edit! -->
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p><DT><A HREF="http://kde.org/" TAGS="Desktop,FLOSS">KDE - Experience Freedom!</A>
<DT><A HREF="https://www.youtube.com/watch?v=zcvU6EoKbaM" TAGS="">Build A Home Server For Your Music and Movies With FreeNAS! - YouTube</A>
<DT><A HREF="https://www.youtube.com/watch?v=Pc9zB1mhPyQ" TAGS="">Create you own cloud storage using owncloud - YouTube</A>
<DT><A HREF="https://www.youtube.com/watch?v=70pCBnNPdew" TAGS="">ownCloud 6 New Features - YouTube</A>
<DT><A HREF="https://www.youtube.com/watch?v=l0oa_YtVLOc" TAGS="">ownCloud Demonstration - YouTube</A>
<DT><A HREF="http://symfony.com/" TAGS="">High Performance PHP Framework for Web Development - Symfony</A>
<DT><A HREF="https://drupal.org/" TAGS="">Drupal - Open Source CMS | Drupal.org</A>
<DT><A HREF="https://identi.ca/" TAGS="">Welcome - Identi.ca</A>
<DT><A HREF="https://www.youtube.com/" TAGS="">YouTube</A>
<DT><A HREF="https://www.google.com/" TAGS="Search Engine">Google</A>
</DL><p>
```

Then import, refresh the bookmark page and see that the tags do not show.

Optionally. The following show further test to try.

Import the following, which is just one bookmark to update:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
It will be read and overwritten.
Do Not Edit! -->
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p><DT><A HREF="https://www.google.com/" TAGS="Search Engine">Google</A>
</DL><p>
```

Import the following, which tries to add to a tagged bookmark which already has tags:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
It will be read and overwritten.
Do Not Edit! -->
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p><DT><DT><A HREF="http://kde.org/" TAGS="Desktop,FLOSS,cool">KDE - Experience Freedom!</A>
</DL><p>
```

Import the following to try adding a new bookmark with tags:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
It will be read and overwritten.
Do Not Edit! -->
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p><DT><DT><A HREF="https://github.com/owncloud/bookmarks" TAGS="FLOSS,cool,source code">GitHub - OwnCloud Bookmark App</A>
</DL><p>
```

Import the following to change the title of the google.com bookmark:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
It will be read and overwritten.
Do Not Edit! -->
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p><DT><A HREF="https://www.google.com/" TAGS="Search Engine">THE Google GENIE!!!!!!!!!!!!!!!!!</A>
</DL><p>
```
# php console.php -V

ownCloud version 6.0.2

### PR DESCRIPTION
**Pull request by marcelklehr**
Wouldn't update tags on existing bookmarks.

Fixes #69 (just noticed :D)

### CODE REVIEW

**Comment by blizzz** [comment]
hm, are those ci issues new?

**Comment by marcelklehr** [comment]
I'm not sure what's up with nextcloud master, I'm gonna fix the pgsql issues now.

**Comment by marcelklehr** [comment]
The tests on master fail with
```
PHP Warning:  require_once(PHPUnit/Autoload.php): failed to open stream: No such file or directory in /home/travis/build/nextcloud/server/apps/bookmarks/tests/bootstrap.php on line 8
```

Apparently this doesn't work (anymore?): 

https://github.com/nextcloud/bookmarks/blob/master/tests/bootstrap.php#L7-L8

**Comment by marcelklehr** [comment]
All tests pass now except the ones on nextcloud master. Could you take a look at that?

**Comment by blizzz** [comment]
I added a commit, not sure where this will break :) but i cannot enable bookmarks due to some DB index issue

**Comment by marcelklehr** [comment]
I changed the db schema in the new ui pr, maybe you need to trigger migrations somehow.

**Comment by blizzz** [comment]
Master failures are now different :D a step forward.

As to my DB issue, it seems the key is too long (perhaos just with utf8mb4?)

```
An exception occurred while executing 'CREATE TABLE `oc_bookmarks` (`id` INT AUTO_INCREMENT NOT NULL, `url` VARCHAR(4096) DEFAULT '' NOT NULL, `title` VARCHAR(4096) DEFAULT '' NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `description` VARCHAR(4096) DEFAULT '' NOT NULL, `public` SMALLINT DEFAULT 0, `added` INT UNSIGNED DEFAULT 0, `lastmodified` INT UNSIGNED DEFAULT 0, `clickcount` INT UNSIGNED DEFAULT 0 NOT NULL, `image` VARCHAR(4096) DEFAULT NULL, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```

**Comment by marcelklehr** [comment]
Thanks for the fix. The remaining issues are due to a typo in the server code: https://github.com/nextcloud/server/issues/9080

**Comment by blizzz** [comment]
rebased to re-trigger CI

**Pull request merged**
