### PR TITLE
Fix delete tag

### LINKED ISSUE #358: REST: DELETE tags gives 500
Sorry that I need to annoy you once more, but I have encountered another problem.

I can not delete tags. If I try to delete a tag:
DELETE `http://msi-7816:8080/index.php/apps/bookmarks/public/rest/v2/tag?old_name=bla`

I get this exception: `Doctrine\DBAL\Exception\SyntaxErrorException`

### Message
```
An exception occurred while executing 'DELETE FROM "oc_bookmarks_tags" tgs WHERE ("tgs"."tag" = ?) AND ("bm"."user_id" IN (?))' with params ["bla", "14"]:

SQLSTATE[HY000]: General error: 1 near "tgs": syntax error
```

### Stacktrace
```
#0 /home/user/Desktop/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/user/Desktop/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM "oc...', Array)
#2 /home/user/Desktop/nextcloud/server/lib/private/DB/Connection.php(213): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM "oc...', Array, Array)
#3 /home/user/Desktop/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('DELETE FROM "oc...', Array, Array)
#4 /home/user/Desktop/nextcloud/server/lib/private/DB/QueryBuilder/QueryBuilder.php(213): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /home/user/Desktop/nextcloud/server/apps/bookmarks/controller/lib/bookmarks.php(377): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /home/user/Desktop/nextcloud/server/apps/bookmarks/controller/rest/tagscontroller.php(38): OCA\Bookmarks\Controller\Lib\Bookmarks->deleteTag('admin', 'bla')
#7 [internal function]: OCA\Bookmarks\Controller\Rest\TagsController->deleteTag('bla')
#8 /home/user/Desktop/nextcloud/server/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
#9 /home/user/Desktop/nextcloud/server/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Bookmarks\Controller\Rest\TagsController), 'deleteTag')
#10 /home/user/Desktop/nextcloud/server/lib/private/AppFramework/App.php(114): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Bookmarks\Controller\Rest\TagsController), 'deleteTag')
#11 /home/user/Desktop/nextcloud/server/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('TagsController', 'deleteTag', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#12 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#13 /home/user/Desktop/nextcloud/server/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#14 /home/user/Desktop/nextcloud/server/lib/base.php(997): OC\Route\Router->match('/apps/bookmarks...')
#15 /home/user/Desktop/nextcloud/server/index.php(40): OC::handleRequest()
#16 {main}
```

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #358

### CODE REVIEW

**Comment by blizzz** [comment]
with and without the patch I am only getting 405s 😕

**Comment by marcelklehr** [comment]
@blizzz The only way you could get a 405 is this: https://github.com/nextcloud/bookmarks/blob/master/controller/rest/tagscontroller.php#L35

**Comment by blizzz** [comment]
nope, bad request is 400, method not allowed gives 405

**Comment by blizzz** [comment]
PEBCAK. missed the index.php 🤦‍

**Pull request merged**
